# Generated by Django 5.1.3 on 2026-06-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("logo", models.URLField(blank=True, default="")),
                ("rank", models.IntegerField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("avatar", models.URLField(blank=True, default="")),
                ("position", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
