# Generated by Django 5.1.3 on 2026-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="avatar",
            field=models.ImageField(blank=True, default="", upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(blank=True, default="", upload_to="logos/"),
        ),
    ]
