# Generated by Django 5.1.3 on 2026-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_player_avatar_alter_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="song",
            field=models.FileField(blank=True, default="", upload_to="songs/"),
        ),
    ]
