# Generated by Django 5.1.3 on 2026-09-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="acceleration",
            field=models.PositiveIntegerField(default=0, verbose_name="加速"),
        ),
        migrations.AddField(
            model_name="player",
            name="aggression",
            field=models.PositiveIntegerField(default=0, verbose_name="积极性"),
        ),
        migrations.AddField(
            model_name="player",
            name="attacking_awareness",
            field=models.PositiveIntegerField(default=0, verbose_name="进攻意识"),
        ),
        migrations.AddField(
            model_name="player",
            name="balance",
            field=models.PositiveIntegerField(default=0, verbose_name="平衡"),
        ),
        migrations.AddField(
            model_name="player",
            name="ball_control",
            field=models.PositiveIntegerField(default=0, verbose_name="控球"),
        ),
        migrations.AddField(
            model_name="player",
            name="ball_winning",
            field=models.PositiveIntegerField(default=0, verbose_name="抢球"),
        ),
        migrations.AddField(
            model_name="player",
            name="condition",
            field=models.PositiveIntegerField(default=0, verbose_name="状态持续性"),
        ),
        migrations.AddField(
            model_name="player",
            name="curl",
            field=models.PositiveIntegerField(default=0, verbose_name="弧线球"),
        ),
        migrations.AddField(
            model_name="player",
            name="defensive_awareness",
            field=models.PositiveIntegerField(default=0, verbose_name="防守意识"),
        ),
        migrations.AddField(
            model_name="player",
            name="dribbling",
            field=models.PositiveIntegerField(default=0, verbose_name="盘球"),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_awareness",
            field=models.PositiveIntegerField(default=0, verbose_name="守门员意识"),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_catching",
            field=models.PositiveIntegerField(default=0, verbose_name="守门员接球能力"),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_clearing",
            field=models.PositiveIntegerField(default=0, verbose_name="守门员解围"),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_reach",
            field=models.PositiveIntegerField(default=0, verbose_name="守门员臂展"),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_reflexes",
            field=models.PositiveIntegerField(default=0, verbose_name="守门员扑救反应"),
        ),
        migrations.AddField(
            model_name="player",
            name="heading",
            field=models.PositiveIntegerField(default=0, verbose_name="头球"),
        ),
        migrations.AddField(
            model_name="player",
            name="injury_resistance",
            field=models.PositiveIntegerField(default=0, verbose_name="抗受伤程度"),
        ),
        migrations.AddField(
            model_name="player",
            name="jumping",
            field=models.PositiveIntegerField(default=0, verbose_name="跳跃"),
        ),
        migrations.AddField(
            model_name="player",
            name="kicking_power",
            field=models.PositiveIntegerField(default=0, verbose_name="脚下力量"),
        ),
        migrations.AddField(
            model_name="player",
            name="lofted_pass",
            field=models.PositiveIntegerField(default=0, verbose_name="空中传球"),
        ),
        migrations.AddField(
            model_name="player",
            name="low_pass",
            field=models.PositiveIntegerField(default=0, verbose_name="地面传球"),
        ),
        migrations.AddField(
            model_name="player",
            name="physical_contact",
            field=models.PositiveIntegerField(default=0, verbose_name="身体接触"),
        ),
        migrations.AddField(
            model_name="player",
            name="set_play",
            field=models.PositiveIntegerField(default=0, verbose_name="定位球"),
        ),
        migrations.AddField(
            model_name="player",
            name="shooting",
            field=models.PositiveIntegerField(default=0, verbose_name="射门"),
        ),
        migrations.AddField(
            model_name="player",
            name="speed",
            field=models.PositiveIntegerField(default=0, verbose_name="速度"),
        ),
        migrations.AddField(
            model_name="player",
            name="stamina",
            field=models.PositiveIntegerField(default=0, verbose_name="体力"),
        ),
        migrations.AddField(
            model_name="player",
            name="tight_control",
            field=models.PositiveIntegerField(default=0, verbose_name="紧密控球"),
        ),
        migrations.AddField(
            model_name="player",
            name="weak_foot_accuracy",
            field=models.PositiveIntegerField(default=0, verbose_name="非惯用脚精准度"),
        ),
        migrations.AddField(
            model_name="player",
            name="weak_foot_usage",
            field=models.PositiveIntegerField(default=0, verbose_name="非惯用脚频率"),
        ),
    ]
