# Generated by Django 5.1.3 on 2026-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_player_acceleration_player_aggression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=1000, verbose_name="积分"),
        ),
    ]
