# Generated by Django 5.1.3 on 2026-09-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_team_points"),
        ("tournaments", "0006_match_points_settled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="变动量")),
                ("points_after", models.IntegerField(verbose_name="变动后积分")),
                (
                    "reason",
                    models.CharField(
                        choices=[("match", "比赛"), ("manual", "手动调整"), ("reset", "重置")],
                        default="match",
                        max_length=10,
                        verbose_name="原因",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_changes",
                        to="tournaments.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_changes",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["team", "-created_at"],
                        name="teams_point_team_id_b3d1b2_idx",
                    )
                ],
            },
        ),
    ]
