# Generated by Django 5.1.3 on 2026-06-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, default="", upload_to="avatars/"),
        ),
    ]
