# Generated by Django 5.1.3 on 2026-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feeditem",
            name="video_url",
        ),
        migrations.AddField(
            model_name="feeditem",
            name="video",
            field=models.FileField(blank=True, default="", upload_to="videos/"),
        ),
    ]
