# Generated by Django 5.1.3 on 2026-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentteam",
            options={"ordering": ["rank"]},
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="赛事排名"),
        ),
    ]
