# Generated by Django 5.1.3 on 2026-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_alter_tournamentteam_options_tournamentteam_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="icon",
            field=models.ImageField(
                blank=True, default="", upload_to="tournament_icons/"
            ),
        ),
    ]
