# Generated by Django 5.1.3 on 2026-09-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournament_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["round", "match_date", "id"]},
        ),
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.PositiveIntegerField(default=1, verbose_name="轮次"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[("swiss", "瑞士轮"), ("knockout", "淘汰赛"), ("league", "循环赛")],
                default="swiss",
                max_length=20,
                verbose_name="赛制",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="rounds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="总轮数"
            ),
        ),
    ]
