# Generated by Django 5.1.3 on 2026-09-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournaments",
            "0004_alter_match_options_match_round_tournament_format_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentteam",
            options={},
        ),
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.PositiveIntegerField(default=0, verbose_name="当前轮次"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="round_interval_days",
            field=models.PositiveIntegerField(default=3, verbose_name="每轮间隔天数"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="stage_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未开始"),
                    ("ongoing", "进行中"),
                    ("finished", "已结束"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="赛事状态",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="losses",
            field=models.PositiveIntegerField(default=0, verbose_name="负"),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="status",
            field=models.CharField(
                choices=[("alive", "存活"), ("advanced", "已晋级"), ("eliminated", "已淘汰")],
                default="alive",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="wins",
            field=models.PositiveIntegerField(default=0, verbose_name="胜"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[("swiss", "晋级瑞士轮"), ("knockout", "淘汰赛"), ("league", "循环赛")],
                default="swiss",
                max_length=20,
                verbose_name="赛制",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rounds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="总轮数上限"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentteam",
            name="rank",
            field=models.IntegerField(blank=True, null=True, verbose_name="最终名次"),
        ),
    ]
