# Generated by Django 5.1.3 on 2026-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_alter_tournamentteam_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="points_settled",
            field=models.BooleanField(default=False, verbose_name="积分已结算"),
        ),
    ]
