# Generated by Django 5.1.3 on 2026-09-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_match_points_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="knockout",
            field=models.BooleanField(default=False, verbose_name="淘汰赛阶段"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="knockout_after_swiss",
            field=models.BooleanField(default=False, verbose_name="瑞士轮后接单败淘汰赛"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="phase",
            field=models.CharField(
                choices=[("swiss", "瑞士轮"), ("knockout", "淘汰赛"), ("finished", "已结束")],
                default="swiss",
                max_length=20,
                verbose_name="当前阶段",
            ),
        ),
    ]
