# Generated by Django 5.1.3 on 2026-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_match_knockout_tournament_knockout_after_swiss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="bracket_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "普通/瑞士"),
                    ("winners", "胜者组"),
                    ("losers", "败者组"),
                    ("final", "总决赛"),
                ],
                default="",
                max_length=10,
                verbose_name="双败轨道",
            ),
        ),
        migrations.AddField(
            model_name="tournamentteam",
            name="elim_band",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="双败淘汰名次段"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("swiss", "晋级瑞士轮"),
                    ("knockout", "淘汰赛"),
                    ("league", "循环赛"),
                    ("double_elim", "双败淘汰"),
                ],
                default="swiss",
                max_length=20,
                verbose_name="赛制",
            ),
        ),
    ]
