# Generated by Django 5.1.3 on 2026-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_add_double_elim"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="stats_settled",
            field=models.BooleanField(default=False, verbose_name="战绩已结算"),
        ),
    ]
