# Generated by Django 5.1.3 on 2026-09-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_pointschange"),
        ("tournaments", "0009_match_stats_settled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerHonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="荣誉名称")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("legend", "殿堂级"),
                            ("gold", "金"),
                            ("silver", "银"),
                            ("bronze", "铜"),
                        ],
                        default="gold",
                        max_length=10,
                        verbose_name="荣誉等级",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="honors/", verbose_name="专属图片"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honors",
                        to="teams.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                        verbose_name="关联赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "队员荣誉",
                "verbose_name_plural": "队员荣誉",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamHonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="荣誉名称")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("legend", "殿堂级"),
                            ("gold", "金"),
                            ("silver", "银"),
                            ("bronze", "铜"),
                        ],
                        default="gold",
                        max_length=10,
                        verbose_name="荣誉等级",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="honors/", verbose_name="专属图片"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honors",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                        verbose_name="关联赛事",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍荣誉",
                "verbose_name_plural": "队伍荣誉",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
